spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nombre_base_datos
spring.datasource.username=nombre_usuario
spring.datasource.password=contraseña_usuario

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

security.jwt.key.private=alguna_clave_privada_para_jwt
security.jwt.user.generator=usuario_generador_jwt
